### ISSUE TITLE
[RFC] cookbook template

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#13]
## [RFC] Providing a template cookbook

Whenever a new cookbook is "adopted" by our team, we have a whole bunch of common patterns to apply. Here's a some guidance to common resources, tools, processes and situations.

This is just a guide, it's not a requirement. If it doesn't make sense in your case, that's fine. Feel free to ignore it, or (even better!) update this doc to mention when it doesn't.

Please update this with your thoughts, comments, questions, concerns, and constructive criticism
### File Structure

Create examples of:
- `attributes/default.rb`
- `definitions/`
- `doc/credit.md`
- `doc/overview.md`
- `libraries/`
- `providers/default.rb`
- `recipes/default.rb`
- `resources/default.rb`
- `templates/default/`
- `test/integration/default/bats/default.bats`
- `test/unit/default_spec.rb`
- `.gitignore`
- `.kitchen.yml`
- `.rubocop.yml`
- `.travis.yml`
- `Berksfile`
- `Gemfile`
- `LICENSE`
- `README.md`
- `Rakefile`
- `metadata.rb`
### Tools

In the documentation, point to resources for:
- `bundler`
- `chefspec`
- `knife-cookbook-doc`
- `rake`
- `rubocop`
- `serverspec`
- `test-kitchen`
- `travis-ci`
### Processes

In the documentation, describe:
- [ ] installing dependencies
- [ ] running a unit test
- [ ] running an integration test
- [ ] linting the code
- [ ] building the doc
- [ ] bumping a revision
- [ ] triggering an automated build
- [ ] building a release package
- [ ] publishing a new release
### Situations

In the documentation, provide guidance to:
- [ ] incrementing revisions
- [ ] identifying testable situations and how to automate those tests
- [ ] testing by unit vs integration
- [ ] integrations for logging, process management, metrics, alerting
- [ ] when to require tests for a patch

**Comment by zuazo** [comment]
Thanks @josephholsten, your list is very complete. I am very interested in helping to create this kind of documentation.

Once we have the complete recommendations, we could create a flavor gem with [`chef-gen-flavors`](https://github.com/Nordstrom/chef-gen-flavors). But I'm not sure if this will be compatible with `knife-cookbook-doc`.

I will give some suggestions based on my experience:

### Documentation Files

I understand that these documents will have links to the common documentation. Maybe we should create a repository called `docs/` for this purpose? is `meta` OK for this?

To your list, I would add the following:
- `CONTRIBUTING.md`: This will add a link to the file when a contributor opens an issue in GitHub. See [here](https://github.com/blog/1184-contributing-guidelines).
- `CHANGELOG.md`: I like to have the history of changes inside the Git repository.

### Unit Tests

I would change the directory structure to the following:
- ~~`test/unit/default_spec.rb`~~
- `test/unit/spec_helper.rb`: Some common RSpec/ChefSpec configuration.
- `test/unit/recipe/default_spec.rb`: ChefSpec tests for recipes, `::default` recipe in this case.
- `test/unit/resources/default_spec.rb`: ChefSpec tests for LWRPs, _default_ LWRP in this case. These tests will [step into LWRPs](https://github.com/sethvargo/chefspec#testing-lwrps).
- `test/unit/libraries/`: **RSpec** tests for cookbook libraries. Recommended for cookbooks with many and big libraries.

### Integration Tests

I prefer Serverspec tests to bats tests. [Chef also recommends Serverspec instead of bats](https://www.chef.io/blog/2015/04/21/overview-of-test-driven-infrastructure-with-chef/):

> However, it is platform specific to Unix/Linux systems that have bash installed, so it does not work on Windows systems. This makes it more difficult to test cross-platform cookbooks, so many users prefer Serverspec. As Serverspec is also the basis of Chef audit mode, it is more widely used, and we recommend Serverspec over BATS for post-convergence testing.

So:
- ~~`test/integration/default/bats/default.bats`~~
- `test/integration/default/serverspec/spec_helper.rb`
- `test/integration/default/serverspec/default_spec.rb`
- `test/integration/default/serverspec/Gemfile`: Optional but recommended to ensure the correct version of Serverspec is used.

#### Testing Cookbooks

Sometimes you require another cookbook to properly test your cookbook. For example to test the Resources, LWRPs, or testing custom and complex use cases. I create them here:
- `test/cookbooks/`

### Some Other Tools to Consider

#### [Guard](https://github.com/guard/guard)

You run `$ guard` and, while you are working in your cookbook, runs the tests whenever a file is changed. Really easy to use.

Files to add:
- `Guardfile`: Pretty simple, always the same.

#### [YARD](http://yardoc.org/)

I usually use this Ruby documentation tool to add documentation to the cookbook libraries. See [an example here](https://github.com/onddo/encrypted_attributes-cookbook/blob/master/libraries/encrypted_attributes_helpers.rb) and [the resulting documentation here](http://www.rubydoc.info/github/onddo/encrypted_attributes-cookbook/master/Chef/EncryptedAttributesHelpers).

Files to add:
- `.yardopts`: Recommended to generate the documentation in [RubyDoc.info](http://www.rubydoc.info/). Always the same content.
- `.inch.yml`: [Inch CI](http://inch-ci.org/) is a site to help you with the documentation process. Mainly recommendations and a badge. Always the same content.

### Some Other Files to Consider
- `libraries/matchers.rb`: ChedSpec matchers for the resources.
- `Vagrantfile`: Deploy the cookbook using Vagrant.
- `Dockerfile` + `.dockerignore`: Deploy the cookbook inside a Docker container.
- `.foodcritic`: Disable some Foodcritic checks.

### More Processes
- [ ] how to contribute, general steps and how to create a PR
- [ ] deploy using vagrant
- [ ] deploy using docker

**Comment by dblessing** [comment]
How does a gem work? I've never seen that. Another option is to create a generator cookbook that 'chef generate' command can use. We've done this internally and it has all the pieces for spec, kitchen, knife doc, etc. I can share it if it's helpful. There shouldn't be much proprietary. If there is I'll remove it

**Comment by josephholsten** [comment]
ok, I'm going to start a template-cookbook repo and paste this stuff in

**Comment by josephholsten** [comment]
@zuazo I've merged your stuff with mine and put it in the readme of https://github.com/chef-brigade/cookbook-skeleton

@dblessing you're exactly on target, that's what `chef-gen-flavors` does: package up a `chef generate cookook` template into a reusable package.

I'm closing this. Any future discussion should happen in the skeleton repo.
