### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by dblessing** [sous-chefs/meta#6]
@josephholsten It would be great to see the Chef Brigade gain momentum. I have a couple of thoughts I want to write down to get the ball rolling. Recent conversation in the chef list (it's a long conversation, but pertinent pieces start with Adam Jacob's comments) at http://lists.opscode.com/sympa/arc/chef/2015-06/msg00314.html has definitely caused me to think about this. I do think there is a large need for an overarching group that can step in and reclaim a project given a specific set of rules - such as the maintainer abandoning the project. It would be beneficial for this group to define those set of rules so that the larger community understands the potential benefits. I'm not sure what you would call this - governing documents, etc.
- Define a small group of individuals to serve as "admins" of the Chef Brigade. This can be fluid, as certainly some admins' interest will diminish and they will move on to other things. This list should probably not be too large but should be responsive. 
- Define a set of rules by which an admin(s) may step in. Potential scenarios:
  - A maintainer no longer wishes to maintain a cookbook. The 'ownership' will be returned to the brigade where a new maintainer is sought.
  - A maintainer goes dormant and does not respond to PRs/issues for a set period of time. A brigade admin will attempt to contact the current maintainer and the maintainer will have 30 days to respond. If no response is received the brigade will seek a new maintainer.
  - A maintainer continuously violates a Code of Conduct (this is one that will need thought through on how to appropriately handle problems. What constitutes an offense requiring removal as a maintainer?)
  - Others?
- Consider having a Supermarket account for Chef Brigade that admins have access to. All cookbooks within the brigade will have this Chef Brigade Supermarket account listed as the 'owner' on Supermarket. The lead maintainer(s) will also be listed in the Supermarket so they can deploy the cookbook. The purpose of this is to ensure the brigade has the ability to reclaim control of that cookbook namespace should the maintainer leave without any contact.

There are 2 main goals that I see the Chef Brigade filling.
1. To preserve the future of cookbooks. Maintainers interests change over time. When one maintainer moves on, the brigade should be able to appoint new maintainers and also retain control of the Supermarket namespace.
2. To foster a welcoming and safe community for all Chef users.

I do not think the Chef Brigade should be in the business of dictating, or involving themselves, in the day-to-day maintenance of the cookbooks. If there is a lead maintainer(s) and things are going well the Brigade administration should stand back. I'm also afraid of too much 'red tape' as cookbook authors will have less interest in becoming involved. Also, it should be understood that just because Chef Brigade 'owns' a cookbook does not mean it will be maintained. In the absence of a willing maintainer the cookbook may go dormant. 

What do you think?

**Comment by luishdez** [comment]
:+1: I fully agreed to this

**Comment by luishdez** [comment]
@chef-brigade/chef-de-partie sorry guys to ping you all… thoughts on this?

**Comment by juliandunn** [comment]
This all sounds good to me.

**Comment by rex** [comment]
This all sounds great to me as well. Our primary focus should be in shepherding cookbooks toward interested and active maintainers and development should remain secondary. The tricky part IMO will be just getting the ball rolling. 
- How do we foster trust with the community? 
- What community are we even targeting to foster trust in?
- How do we prove that we have what it takes to revive and maintain these packages? 
- How do we convince disinterested or stagnant maintainers to hand over control of these cookbooks? 
- Many cookbook authors that appear disinterested or to have abandoned the project are in actuality just under the impression that the package is in a stable state and does not require maintenance. How do we filter these packages/authors out or convince them that _no software_ is inherently stable and that maintenance must continue? 

Just some thoughts. Eager to hear feedback.

**Comment by lamont-granquist** [comment]
Something you should consider is joint ownership.  In the case where there's a maintainer who just hasn't had the time lately you don't necessarily need to take that ownership away from them.  The same goes for joint ownership with Chef, Inc as well.  That can also take any sting away from it since you don't have to treat it as "handing over control" but just adding more people to help out.

I'm also not certain that maintainers are under the impression that their cookbooks are stable.  I suspect most of them just don't have the time to spend on use cases that aren't ones that they're most concerned with.  The issues that pile up should make it pretty clear to the authors that their cookbooks aren't stable.

**Comment by zarry** [comment]
I second all of the original post as well.  

I tend to agree with @lamont-granquist on the idea that owners at least have some idea the cookbook isn't meeting the needs of every use case(which shouldn't be expected) as they receive emails / github notifications when issues or PRs pop up.   Joint ownership makes sense to me in this case.  It is not always the easiest process to find active maintainers to step in and help you with the workload.  In that case we work with the cookbook owner to find some active maintainers but during the process we may have joint ownership.

I think most of what @rex asks we can answer by simply doing a fantastic job with the cookbooks we currently manage.  Trust will come as we churn out quality work.  We have a cookbook in front of us with mongodb that was in a pretty rough state but also has a pretty substantial user base.  If we can work to resolve those issues in a timely fashion while long term finding an owner for the cookbook I think we would have done exactly what we set out to do.  At the same time we would be earning the trust with the work behind us to show for it.

Let's keep the process to a minimum and work on improving cookbooks in the community.

**Comment by dblessing** [comment]
@lamont-granquist  Great idea about the joint ownership and adding new maintainers as opposed to removing old.

**Comment by lamont-granquist** [comment]
It may actually make sense to make the "Chef Brigade" as wide of a group as possible.  Instead of having Chef Inc working on the chef-cookbooks and opscode-cookbooks, and chef-brigade members working on these cookbooks, and hw-cookbooks being worked on by heavywater employees, if they were all just in a single repo and all the members had commit and admins rights (chef-brigade, plus Chef Inc, plus heavywater) then there would be the least amount of friction involved in getting changes published.  And I'm just picking on heavywater because they've got a bunch of community cookbooks and I got blocked recently where I would have liked to have commit bits to merge an outstanding PR on one of their cookbooks.  There's other organizations out there with large numbers of curated cookbooks as well, along with some individuals that do good work curating sets of cookbooks.  We should pull them all under the same banner.

I think that is where this should end up eventually if its successful.

And I guess there's a philosophical point here that these are supposed to be "community" cookbooks, but each one is typically owned by one or two people who absolutely control commit bits to the repos.  And we keep on constructing little fiefdoms of cookbooks (chef-cookbooks, opscode-cookbooks, hw-cookbooks).  When the big initial fiefdom failed (opscode-cookbooks) we broke it up into a hundred small fiefdoms and that failed.  That is most likely the root of the broken model.

**Comment by lamont-granquist** [comment]
issue #1 and redguide makes my point even better

**Comment by rex** [comment]
@lamont-granquist You've made several points with which I agree _absolutely_. You've made an important distinction that I feel we should make a tenet of our mission here: **assuming joint ownership** of a cookbook versus **assuming control** of said cookbook. Joint ownership gives us everything that we would need to perform the task we are setting out to accomplish - maintaining abandoned or otherwise neglected cookbooks. We **are not** attempting to forcibly wrest ownership of the cookbooks from the original author. We are merely on a mission to help authors who have moved on or haven't the time to maintain their cookbooks. 

I think the driving points here should be "adopting" as many cookbooks as we possibly can, identifying and resolving existing issues in those cookbooks, and quickly resolving issues that arise in them.

**Comment by dblessing** [comment]
I'm not particularly in favor of a few of the last suggestions - every cookbook under Chef Brigade, IMO, _must_ have specified maintainers. It should not just be a 'free-for-all' of all the brigade members. Maintainers who are merging PRs should have a vested interest and at least some knowledge of the problem the cookbook tries to solve. Otherwise it can quickly become a mess. I'm completely fine with there being a multitude of maintainers but I believe the people interested in helping with a cookbook should be listed in the README. Others should not be merging without identifying themselves as maintainers first.

**Comment by rex** [comment]
@dblessing I wholeheartedly agree that each cookbook must have specified maintainers. Having a free-for-all would lead to chaos and ultimately wouldn't really solve anything.

**Comment by juliandunn** [comment]
It seems like we're narrowing down to two roles:
- Brigade admins, who decide governance for the brigade and also add/remove maintainers (manage ACLs for the cookbooks in the brigade)
- Cookbook maintainers, who have commit bits for the cookbooks they maintain and push bits in Supermarket to upload new versions of those cookbooks

Does that seem right?

**Comment by josephholsten** [comment]
@juliandunn 

Currently I have the following groups.
- Owners: the admins you speak of. Currently, this is just myself and cookbook maintainers.
- Chef de partie: folks with commit bits. Currently, I'm handing them out to anyone who asks.
- Commis: people who want to "join" the brigade, but don't need any access. 

I'd like to have at least 5 members of "Owners" to keep the bus factor down. That means I'm putting any maintainers in owners until we get more than that number.

I'm currently handing out commit bits to anyone who asks, but I'm comfortable letting each maintainer decide the commit bit policy for their cookbook.

**Comment by josephholsten** [comment]
Could you folks review #8? This conversation is good, but I'd like us to actually make a decision ;-)

**Comment by zuazo** [comment]
I agree with @lamont-granquist and @zarry in this matter. Nothing that has not been said, but I tell you my opinion:

I think aggregation is the key here. I'm not against having some kind of basic management structure and some rules. But they should be simple and changeable.

There are so many cookbooks out there in need of love. If we want to make a significant improvement to the cookbook landscape, we will have to do much work and have many eyes watching. As maintainers we will face problems beyond our knowledge and capabilities, not only use cases that seem uninteresting. Being open and generous is best to attract many different people.

Sometimes we are busy during certain time periods and that does not mean we have abandoned the project. Our work flow is not constant. When someone is busy for a whole month for example, there must be another that can do the job without facing bureaucracy. I think that is the problem of abandoned cookbooks.

As it has been said above, we must above all avoid becoming another `opscode-cookbooks` / `small-fiefdom-cookbooks`. And for that we have to do things differently.

**Comment by rex** [comment]
I could not agree more strongly with @zuazo. Well put. If we expect to do things better than the other guys we have to do things _differently from_ the other guys.
